### ISSUE TITLE
Usage and Deployment

### ISSUE THREAD

**Issue by urras** [jens-na/github-aur#1]
Hello,
I stumbled upon your repo a few days ago, and I think I'm going to use it a lot in the future. As I'm somewhat unfamiliar with the inter-workings of pacman, I'm not sure really how to deploy this correctly, or how to use it in general, as there are no instructions in the README. 

Say I had a large repo to manage, such as [alerque/aur](https://github.com/alerque/aur), how would I use these scripts to manage those AUR packages, given that I hypothetically owned them?

**Comment by jens-na** [comment]
Hi,
there is no documentation or instructions because the project has never been finished. This project was just a starting point how to upload packages in a more convenient way... Sorry. 

The idea was to push the PKGBUILDs to Travis and actually build the packages there (`makepkg --source`). Afterwards the tarball should get uploaded to the AUR with [aurup](http://www.pierloz.com/Aurup/).

The Travis CI system is using Ubuntu I think, so I need to compile pacman myself and install it on this machine to create the source tarballs of the packages... This is where things got complicated and frustrating.

Sorry that this project won't help you to upload your packages, but maybe you should take a look at the project [aurup](http://www.pierloz.com/Aurup/), it lets you upload your source tarballs to the AUR with a command line tool. Maybe it suits your use case.

But if you have any ideas or code how to upload packages with Travis you can open an issue or a pull request. :)

**Comment by urras** [comment]
Okay, thanks so much :+1:
